Feature/configure sms bot from db
vessels-tech/sms-bot pull request #17
Opened 2017-04-28 00:21 UTC by lewisdaly

This is a pretty mammoth change, but surprisingly, it's cleared up a lot of the Thread, ConversationDelegate and ConversationRouter logic.

I've tested locally, but this might break the deployment, as we will need to re-seed the db etc.

2017-04-28 03:26 UTC, kevindoveton requested changes
not sure why tests are failing - worked fine on my computer

2017-04-28 03:26 UTC, kevindoveton commented on .gitignore
> +bundle.js.map
should the entire dist directory be ignored?

2017-04-28 03:26 UTC, kevindoveton commented on deployment/tag_and_push_docker.sh
> +DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../ && pwd )"
you dont use this?

2017-04-28 03:26 UTC, kevindoveton commented on sms-bot/src/message/FacebookRouter.js
>                console.log(msg)
can probably remove the log // my bad

2017-04-28 04:24 UTC, lewisdaly commented on .gitignore
> +bundle.js.map
Nah, the production running docker container actually looks for the index.html file in dist. Not ideal, but the best I could do after 30 mins of dealing with webpack

2017-04-28 23:55 UTC, merged

2017-04-29 04:29 UTC, kevindoveton commented
facebook bot is broken

2017-04-29 05:44 UTC, lewisdaly commented
Ok. I'll check it out